import React from 'react';

const boxesData = [
  {
    subheading: 'General',
    content: `These Terms of Use constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”) and concerning your access to and use of the Website and the Services. You agree that by accessing the Services, you have read, understood, and agree to be bound by all of these Terms of Use.

      IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF USE, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.`,
  },
  {
    subheading: 'OUR WEBSITE AND SERVICES',
    content: `We are not lawyers nor a law firm, but we help you with compliance in relation to your privacy and contractual obligations. We provide you a software (the “Software”), that you access remotely via the cloud, that you can use for (a) consent management (“Consent Platform”); and (b) the generation of policies, legal agreements, disclaimers, and other documents generated by the Services using information related to your business or organization that you enter into the Software (collectively “Forms”).

    The information, Consent Platform, and Forms provided when using the Services are not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country. Accordingly, those persons who choose to access the Services from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.
    `,
  },
  {
    subheading: 'INTELLECTUAL PROPERTY RIGHTS',
    content: `Unless otherwise indicated, we retain all right, title, and interest in and to the Software and the Website, including without limitation all graphics, user interfaces, databases, functionality, software, website designs, audio, video, text, photographs, graphics, logos, and trademarks or service marks reproduced through the System. These Terms of Use do not grant you any intellectual property license or rights in or to the Software and the Website or any of its components, except to the limited extent that these Terms of Use specifically sets forth your license rights to it. You recognize that the Software and the Website and their components are protected by copyright and other laws.

    Conditioned upon your compliance with these Terms of Use and, if applicable, your payment of the Subscription Fees, we grant you the rights to reproduce, modify, and publicly display the Forms and use the Consent Platform (all together “Content”) on your website or mobile application. In addition, as to a Form intended to serve as a legal agreement between you and a counterparty, we grant you the right to distribute that Form to the counterparty to the extent reasonably necessary for your counterparty to execute the agreement. Under no circumstances may you use the Forms and use the Consent Platform for commercial purposes other than to facilitate compliance with applicable laws and best practices or the execution of agreements by your own business or organization. The Forms and the Consent Platform generated by the Software are licensed, not sold, and you receive no title to or ownership of the Forms or the Consent Platform.
    `,
  },
  {
    subheading: 'USER REPRESENTATIONS',
    content: `By using the Services, you represent and warrant that: (1) all registration information you submit will be true, accurate, current, and complete; (2) you will maintain the accuracy of such information and promptly update such registration information as necessary; (3) you have the legal capacity and you agree to comply with these Terms of Use; (4) you are not a minor in the jurisdiction in which you reside; (5) you will not access the Services through automated or non-human means, whether through a bot, script or otherwise; (6) you will not use the Services for any illegal or unauthorized purpose; and (7) your use of the Services will not violate any applicable law or regulation.
    
    If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof).
    `
  }
  // Add more objects for additional boxes
];

const TermsAndConditions = () => {
  return (
    <div>
        <div className="container" style={{ maxWidth: '1200px', margin: '100px auto', padding: '20px'}}>
            <h1 style={{ textAlign: 'center', marginBottom: '10px', fontSize:'60px', fontWeight:'bold'}}>Privacy Policy</h1>
        </div>
        {boxesData.map((box, index) => (
            <div key={index} className="container" style={{ maxWidth: '1200px', margin: '20px auto', padding: '20px' }}>
            <div className="terms-content" style={{ backgroundColor: '#f9f9f9', borderRadius: '5px', padding: '20px' }}>
                <h2 className="subheading" style={{ marginBottom: '20px', color: '#888', fontSize:'30px'}}>{box.subheading}</h2>
                <p className="paragraph" style={{ lineHeight: '1.6', fontSize:'18px', whiteSpace:'pre-line'}}>{box.content}</p>
            </div>
            </div>
        ))}
    </div>
  );
};

export default TermsAndConditions;
